# cloudbuild.yaml
# 23.1.24
# ALLUVIO Aternity Tech Community Cookbook (https://github.com/Aternity/Tech-Community)
#
# Usage:
#   
#   gcloud builds submit --config cloudbuild.yaml --substitutions _APM_PACKAGE_GSUTIL_URI={_APM_PACKAGE_GSUTIL_URI},_REGION={_REGION},_REPOSITORY={REPOSITORY},_IMAGE_NAME={IMAGE_NAME},_TAG_NAME={TAG_NAME}
#
# Example
#
#   gcloud builds submit --config cloudbuild.yaml --substitutions _APM_PACKAGE_GSUTIL_URI=gs://my_new_bucket/appinternals_agent_latest_linux.gz

steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '${_APM_PACKAGE_GSUTIL_URI}', './aternity-apm-jida-linux.zip']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}']
substitutions:
  _APM_PACKAGE_GSUTIL_URI: gs://my_bucket/aternity-apm-jida-linux-12.19.0_BL516.zip
  _REGION: europe-west9
  _REPOSITORY: apm
  _IMAGE_NAME: cookbook-233
