# Riverbed-Community-Toolkit
# 105-opentelemetry-go-app
# version: 24.10.4

# Exporter
OTEL_TRACES_EXPORTER: otlp

# Jaeger endpoint
JAEGER_PORT: 14268
JAEGER_PATH: /api/traces

# Zipkin endpoint
ZIPKIN_PORT: 9411
ZIPKIN_PATH: /api/v2/spans

# OTLP http endpoint
OTLP_PORT: 4318
OTLP_PATH: /v1/traces

# APM collector configuration
RIVERBED_APM_COLLECTOR_SERVICE_HOST: localhost

# Service name
OTEL_SERVICE_NAME: service105-go

# Server configurations
FRONTEND_SERVICE_HOST: localhost
FRONTEND_SERVICE_PORT: 8081
BACKEND_SERVICE_HOST: localhost
BACKEND_SERVICE_PORT: 9000

# Sleep millis
SLEEP: 5

ADD_CONSOLE_EXPORTER: "off"
