FROM dockercisco/acitoolkit

WORKDIR /opt

COPY aci-endpoint-tracker.patch /tmp

RUN cd /opt/acitoolkit/applications/endpointtracker && \
    patch -b < /tmp/aci-endpoint-tracker.patch

CMD ["sleep infinity"]
