# apm-collector-daemonset.yaml
# 23.08.24
# Riverbed-Community-Toolkit (https://github.com/riverbed/Riverbed-Community-Toolkit)
#
# Deploy the APM Collector as a daemonset a on Kubernetes cluster
# Tested on EKS, GCP and AKS
#
# Usage:
#
#     1. Customize the env variables in the container definition (container name: apm-daemonset-pod-agent)
#
#       replace {{ALLUVIO_ATERNITY_APM_CUSTOMER_ID}}, for example: 12312341234-1234-124356
#       replace {{ALLUVIO_ATERNITY_APM_SAAS_SERVER_HOST}} for example: agents.apm.my-account.aternity.com
#
#     2. Apply  
#
#       kubectl apply -f apm-collector-daemonset.yaml
#
#     3. Check resources
#
#       kubectl --namespace alluvio-aternity get daemonset
#       kubectl --namespace alluvio-aternity get pod
#
#     4. Remove
#
#       kubectl delete -f apm-collector-daemonset.yaml

---
apiVersion: v1
kind: Namespace
metadata:
  name: alluvio-aternity
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: alluvio-aternity
  name: apm-collector-daemonset
  labels:
    app.kubernetes.io/name: daemonset
    app.kubernetes.io/component: apm-collector
    app.kubernetes.io/part-of: alluvio-aternity
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: daemonset
      app.kubernetes.io/component: apm-collector
      app.kubernetes.io/part-of: alluvio-aternity
  template:
    metadata:
      name: apm-collector-daemonset
      labels:
        app.kubernetes.io/name: daemonset
        app.kubernetes.io/component: apm-collector
        app.kubernetes.io/part-of: alluvio-aternity        
    spec:
      hostNetwork: true
      containers:
      - name: aternity-collector
        image: registry.hub.docker.com/aternity/apm-collector:latest
        env:

        # Configure the APM Collector
        - name: ALLUVIO_ATERNITY_APM_CUSTOMER_ID
          value: {{ALLUVIO_ATERNITY_APM_CUSTOMER_ID}} # TODO 1: Replace {{ALLUVIO_ATERNITY_APM_CUSTOMER_ID}} for example: 12312341234-1234-124356
        - name: ALLUVIO_ATERNITY_APM_SAAS_SERVER_HOST
          value: {{ALLUVIO_ATERNITY_APM_SAAS_SERVER_HOST}} # TODO 2: Replace {{ALLUVIO_ATERNITY_APM_SAAS_SERVER_HOST}} for example: agents.apm.myaccount.aternity.com

        - name: SERVER_URL
          value: wss://$(ALLUVIO_ATERNITY_APM_SAAS_SERVER_HOST)/?RPM_AGENT_CUSTOMER_ID=$(ALLUVIO_ATERNITY_APM_CUSTOMER_ID) 
        - name: MGR_DEBUG
          value: "false"

        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 288Mi

        ports:
          - name: otlp # OTLP/gRPC
            hostPort: 4317
            containerPort: 4317
            protocol: TCP
          - name: otlp-http
            hostPort: 4318
            containerPort: 4318
            protocol: TCP
          - name: zipkin # Default endpoint for ZipKin receiver.
            hostPort: 9411
            containerPort: 9411
            protocol: TCP
          - name: jaeger-http # Jaeger Thrift Binary over HTTP
            hostPort: 14268
            containerPort: 14268
            protocol: TCP
          - name: jaeger-compact # Jaeger Thrift Compact
            hostPort: 6831
            containerPort: 6831
            protocol: UDP
          - name: jaeger-binary #  Jaeger Thrift Binary
            hostPort: 6832
            containerPort: 6832 
            protocol: UDP

      tolerations:
        - operator: "Exists"
          effect: "NoSchedule"
        - operator: "Exists"
          effect: "NoExecute"
