# app-with-apm-config.yaml
# version: 240701 - Riverbed Community Toolkit
#
# Usage:
#
#   oc apply -f yourapp-with-apm.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: cookbook-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cookbook-app
  name: yourapp
  labels:
    app.kubernetes.io/name: yourapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: yourapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yourapp
      ###############################################
      # Riverbed APM configuration
      annotations:
        instrument.apm.riverbed/inject-java: "true"
      ###############################################              
    spec:
      containers:
      - name: java-spring-yourapp
        image: springio/gs-spring-boot-docker
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi        
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: cookbook-app
  name: yourapp
spec:
  selector:
    app.kubernetes.io/name: yourapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
