# docker-compose.yaml
#
# Riverbed-Community-Toolkit
# 108-collect-zipkin-nodejs-app
# version: 24.10.4
#
# Compose file to use with the cookbook 108
# a Nodejs webapp with Zipkin instrumentation exporting telemetry to the APM OpenTelemetry Collector
#
# Usage
#   docker-compose up
#
# Example in Bash
#   export RIVERBED_APM_SAAS_SERVER_HOST="agents.apm.myaccount.aternity.com"
#   export RIVERBED_APM_CUSTOMER_ID="12341234-12341234-13241234"
#   docker-compose up
#
# Example in PowerShell
#   $env:RIVERBED_APM_SAAS_SERVER_HOST="agents.apm.myaccount.aternity.com"
#   $env:RIVERBED_APM_CUSTOMER_ID="12341234-12341234-13241234"
#   docker-compose up

services:

  opentelemetry-collector:

    # APM OpenTelemetry Collector
    # https://hub.docker.com/r/aternity/apm-collector

    image: registry.hub.docker.com/aternity/apm-collector:2022.4.0-4

    container_name: riverbed-apm-opentelemetry-collector       

    environment:
    
      SERVER_URL: "wss://${RIVERBED_APM_SAAS_SERVER_HOST}/?RPM_AGENT_CUSTOMER_ID=${RIVERBED_APM_CUSTOMER_ID}"
    
    ports:

      # Uncomment the telemetry protocol used by the application

      # OpenTelemetry, https://opentelemetry.io
      # - "4318:4318/tcp"     # OpenTelemetry OTLP JSON/Protobuf over HTTP
      # - "55681:55681/tcp" # OpenTelemetry OTLP JSON/Protobuf over HTTP
      # - "4317:4317/tcp"   # OpenTelemetry OTLP over gRPC
      
      # Jaeger, https://www.jaegertracing.io
      # - "14268:14268/tcp" # Jaeger Thrift Binary over HTTP
      # - "6831:6831/udp"   # Jaeger Thrift Compact
      # - "6832:6832/udp"   # Jaeger Thrift Binary
      
      # Zipkin, https://zipkin.io
      - "9411:9411/tcp"   # Zipkin v2 json/protobuf and v1 json/thrift
      # - "5775:5775/udp"   # Jaeger's Thrift support for Zipkin v1
      

  service108_js:   
    
    environment:  
    
      ZIPKIN_ENDPOINT: http://riverbed-apm-opentelemetry-collector:9411/api/v2/spans
      ZIPKIN_SERVICE_NAME: service108_js

    ports:
      - "8108:80"

    build:
      context: https://github.com/riverbed/Riverbed-Community-Toolkit.git#master:/APM/108-collect-zipkin-nodejs-app
      dockerfile: Dockerfile
