FROM ubuntu:latest

RUN apt-get update && apt-get -y upgrade && \
    apt-get install --no-install-recommends -y software-properties-common && \
    apt-get install --no-install-recommends -y python3-pip build-essential python3-dev && \
    apt-get install --no-install-recommends -y ansible python3-paramiko sshpass ssh && \
    apt-get install --no-install-recommends -y vim telnet curl iputils-ping && \
    apt-get install --no-install-recommends -y mysql-client

RUN pip3 install steelscript
RUN pip3 install steelscript.appresponse
RUN pip3 install mysql-connector-python

RUN echo "localhost" >> /etc/ansible/hosts

RUN mkdir /usr/lib/python3/dist-packages/ansible/modules/riverbed/
COPY ./modules/service.py /usr/local/lib/python3.8/dist-packages/steelscript/common/
COPY ./modules/aci_mysql*.py /usr/lib/python3/dist-packages/ansible/modules/riverbed/
COPY ./modules/host_group_upload.py /usr/lib/python3/dist-packages/ansible/modules/riverbed/

WORKDIR /app

CMD ["sleep infinity"]
