# cloudbuild.yaml
# 23.1.24
# Riverbed-Community-Toolkit (https://github.com/riverbed/Riverbed-Community-Toolkit)
#
# Usage:
#
#   gcloud builds submit --config cloudbuild.yaml --substitutions _APM_PACKAGE_GSUTIL_URI={_APM_PACKAGE_GSUTIL_URI},_REGION={_REGION},_REPOSITORY={REPOSITORY},_IMAGE_NAME={IMAGE_NAME},_TAG_NAME={TAG_NAME}
#
# Example
#
#   gcloud builds submit --config cloudbuild.yaml --substitutions _APM_PACKAGE_GSUTIL_URI=gs://my_new_bucket/appinternals_agent_latest_linux.gz

steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '${_APM_PACKAGE_GSUTIL_URI}', './apm-customization/appinternals_agent_latest_linux.gz']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}','-t','${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${_TAG_NAME}','.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','-a','${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}']
substitutions:
  _APM_PACKAGE_GSUTIL_URI: gs://my_bucket/appinternals_agent_latest_linux.gz
  _REGION: europe-west9
  _REPOSITORY: apm
  _IMAGE_NAME: alluvio-aternity-apm-daemonset-pod-agent
  _TAG_NAME: "230124"
